### PR TITLE
Rerender

### PR DESCRIPTION
**Pull request by h-vetinari**

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Can we merge it?

**Comment by h-vetinari** [comment]
Was waiting for input from @xhochy here (due to observed issues with abseil & clang 18). From my POV this should be good.

**Comment by h-vetinari** [comment]
OK, I think this won't hurt

**Comment by rouault** [comment]
I'm not totally sure but somehow suspect this updates to break GDAL conda-forge based builds on Mac ARM64

See https://github.com/OSGeo/gdal/actions/runs/12538381472/job/34964452787?pr=11556 which breaks with:
```
 dyld[24328]: Symbol not found: __ZN4absl12lts_2024072212log_internal10LogMessagelsIhLi0EEERS2_RKT_
  Referenced from: <9D909FE4-9A96-30EE-B086-0169456B43FC> /Users/runner/miniconda3/envs/test/lib/libre2.11.dylib
  Expected in:     <D623F952-8116-35EC-859D-F7F8D5DD7699> /Users/runner/miniconda3/envs/test/lib/libabsl_log_internal_message.2407.0.0.dylib
Subprocess aborted
```

Probably that https://github.com/conda-forge/re2-feedstock/ needs a rebuild?

**Comment by h-vetinari** [comment]
Thanks for the report. Done in https://github.com/conda-forge/re2-feedstock/pull/87

If this turns out to be more widespread, we might have to do something smarter (like a migration). For now I'm hoping these things sort themselves out.

**Comment by rouault** [comment]
> Thanks for the report. Done in [conda-forge/re2-feedstock#87](https://github.com/conda-forge/re2-feedstock/pull/87)

thanks, that helped moving things a bit further. Now next candidate for rebuild is protobuf:
```
yld[23066]: Symbol not found: __ZN4absl12lts_2024072212log_internal10LogMessagelsIiLi0EEERS2_RKT_
  Referenced from: <7DD6F527-7A4A-3649-87B6-D68B25F8B594> /Users/runner/miniconda3/envs/test/lib/libprotobuf.28.2.0.dylib
  Expected in:     <D623F952-8116-35EC-859D-F7F8D5DD7699> /Users/runner/miniconda3/envs/test/lib/libabsl_log_internal_message.2407.0.0.dylib
Subprocess aborted
```

**Comment by philippjfr** [comment]
Probably the same issue but here's the same error on import of pyarrow on Mac Arm64:

https://github.com/holoviz/param/actions/runs/12548243761/job/34987161860#step:3:35

**Comment by h-vetinari** [comment]
Argh, this is drawing wider circles than I had hoped...

**Comment by h-vetinari** [comment]
Opened #87, let's move the discussion there.

**Pull request merged**
