### PR TITLE
abseil v20230125 LTS

### PR DESCRIPTION
**Pull request by h-vetinari**
Seems the bot didn't pick this one up.

### CODE REVIEW

**Comment by njzjz** [comment]
```
#error "C++ versions less than C++14 are not supported."
```

**Comment by h-vetinari** [comment]
> ```
> #error "C++ versions less than C++14 are not supported."
> ```

Yeah, I know, I just forgot to drop them. However, there's some more libs that haven't been properly taken care of on the windows DLL side which I'm just looking into.

**Comment by h-vetinari** [comment]
@conda-forge/abseil-cpp 
This should be good to go. A bunch of patches were upstreamed successfully (with the exception of https://github.com/abseil/abseil-cpp/pull/1115 that's yet to be merged), otherwise this is a pretty standard version bump.

Of course, dropping C++11 raises the question if we should even keep building C++14 and the respective static libs. To the best of my knowledge, all feedstocks in cond-aforge depending on abseil are now on C++17, so arguably this isn't necessary anymore. On the other hand, we haven't fixed the situation with https://github.com/conda-forge/abseil-cpp-feedstock/issues/45 yet, which will only get dicier now that protobuf has started [depending](https://github.com/protocolbuffers/protobuf/releases/tag/v22.0-rc1) on abseil.

So far there shouldn't be many (relevant) ABI differences between C++17 and C++20, but those will very likely arise over time.

CC @conda-forge/core @conda-forge/libprotobuf @coryan @pitrou @rgommers

**Comment by h-vetinari** [comment]
Ah yes, and I wanted to remove the compatibility output for the old name `abseil-cpp`. Based on this [search](https://github.com/search?q=org%3Aconda-forge%20-%20abseil-cpp&type=code) it's not depended upon by a feedstock in conda-forge anymore.

**Review by xhochy — APPROVED** [review]
Removal of the `abseil-cpp` output seems fine.

**Comment by h-vetinari** [comment]
On further reflection, I decided to remove the `libabseil-static` outputs. They did not fulfill their intended role as encapsulating the ABI concerns, and are not in use anywhere AFAIK. They can of course be readded if ever the need arises.

Barring further comments, I'll merge this in 24h.

**Pull request merged**
