### PR TITLE
Try enabling osx/win.

### PR DESCRIPTION
**Pull request by bluescarni**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bluescarni** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
Hi @njzjz ! I enabled the Windows and OSX builds, and, after a couple of tweaks, everything seems to build & install fine.

The Windows build was initially failing because it was being built in Debug mode, and it was running into this bug:

https://github.com/abseil/abseil-cpp/issues/364

I switched the build type to Release and it built.

I also added myself to the maintainers list, as I am interested in maintaining absl on conda.

**Comment by bluescarni** [comment]
> Is it OK to merge?

It is, as far as I am concerned. It it ok for be to be added to the maintainers list?

**Comment by njzjz** [comment]
> > Is it OK to merge?
> 
> It is, as far as I am concerned. Is it ok for me to be added to the maintainers list?

That's fine. Thank you.

**Comment by bluescarni** [comment]
@njzjz Cheers, thanks for the quick response!

**Pull request merged**
